title: Fonts for the web
hero_image: images/banner.png
description: Information on how fonts are used on websites.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-26"
steps:
  - title: Fonts for the web
