---
title: Fontes para a web
hero_image: images/banner.png
description: Informações sobre como as fontes são usadas em sites.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-26"
steps:
  - title: Fontes para a web
