---
title: Polices pour le web
hero_image: images/banner.png
description: Informations sur la façon dont les polices sont utilisées sur les sites web.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-26"
steps:
  - title: Polices pour le web
